### PR TITLE
Rob/least cost battery dispatch model

### PR DESCRIPTION
**Pull request by robstallman**
**Summary**
This PR introduces a new version of the system model in PySAM. The model is new for two main reasons:
1. The battery dispatch model has been revised. In the new model, we take into account geothermal generation. Geothermal generation is treated as a "last-resort" way of meeting the load, because we plan on dispatching the lowest marginal cost generation first to meet the load. Note that in order to produce this model, we made a key assumption (listed below). The rules for dispatching the battery are described [here](https://docs.google.com/document/d/1329N9aiYtVKTnmWwCmpqC2CrzPKWyW0HSiBxBBokFn0/edit?tab=t.0)
2. The system size has been reduced somewhat drastically. The PV has been reduced from 330MW to 230MW (DC). The battery has been reduced from 100MW / 1312MWh to 30MW / 90MWh (DC).

With this update, we are able to meet the load for all hours of the year. Please review the system outputs [here](https://drive.google.com/file/d/1NzevIF7jnUNkMoGXdqwnmSss5puF2Rh4/view?usp=drive_link).

**Key Assumptions**

- The geothermal plant can ramp instantaneously. In reality, this is not the case and we need to either account for the ramp rates in the battery dispatch model or build another battery co-located with the geothermal to smooth the ramping.
- Battery SOC was calculated using coulomb-counting in the battery dispatch model in order to calculate the power target. In reality, this yields a far more accurate SOC than the battery would report in the field (or which SAM has calculated). The result is that the geothermal plant may need to be cycled more. _I assume that this cycling will remain within the nameplate ratings of the geothermal plant, but this is something that we may want to dig deeper into._

### CODE REVIEW

**Review by ecooper-cu — APPROVED** [review]
This looks great Rob, thank you!

**Comment by robstallman** [comment]
Posting an idea here so that I don't forget it later:
We probably need to figure out how to smooth the dispatch of the geothermal generator, and it probably doesn't make sense to do what I suggested above of putting a battery onsite with the geothermal.
What we can do is build two different batteries:
1.  A 4hr, high power battery to meet bulk load
2. A ~1hr, medium power battery colocated with the PV generation and scheduled to dispatch such that it smooths PV variability. This makes the variability seen by the geothermal resource much less extreme, which will probably remain within its ramp limits. Note – it may make sense in this system design to forgo wind generation entirely.

**Comment by annavanboven** [comment]
I like the idea of pairing a battery with the PV! Thanks for working on this!

**Review by annavanboven — APPROVED** [review]

**Comment by annavanboven** [comment]
Looking at the notebook output you linked, I have a few questions:
 - are these dataframes saved anywhere? wind_model_outputs, battery_model_outputs, grid_model_outputs, single_owner_outputs
 - also, is sytem_df what we will want to use to study the metrics?
In general, I think it would be helpful to be able to easily access the information for each test case without re-running the notebook. It all looks great!

**Comment by robstallman** [comment]
@annavanboven I've added the dataframes that you mentioned to the google drive [here](https://drive.google.com/drive/folders/1xDG2KALMSu-ELNNRWAbA3LyRVLdiF2or).

They're too large to upload to git, so I opted to work around this by storing the data in Google Drive.
There's a script to demonstrate accessing the data, but in order to do so you'll need to replace the pickled object filepath with your own path. Gross, but it'll do for now :)

**Pull request merged**
